#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -I ./lib/judy-1.0.5/include
CFLAGS =  -lJudy -lxml2 -lm
RESINC = 
LIBDIR = 
LIB = -L ./lib/judy-1.0.5/lib
LDFLAGS = -lJudy -lxml2 -lm

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -O3 `xml2-config --cflags`
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  $(LDFLAGS) `xml2-config --libs`
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/BlastGraph

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O3 `xml2-config --cflags`
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  $(LDFLAGS) `xml2-config --libs`
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/BlastGraph

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/sequence_4bits.o $(OBJDIR_DEBUG)/src/parser.o $(OBJDIR_DEBUG)/src/misc_tools.o $(OBJDIR_DEBUG)/src/main.o $(OBJDIR_DEBUG)/src/listNodeUint16.o $(OBJDIR_DEBUG)/src/listNodeChar.o $(OBJDIR_DEBUG)/src/list.o $(OBJDIR_DEBUG)/src/Duo.o $(OBJDIR_DEBUG)/src/extendLevenshtein.o $(OBJDIR_DEBUG)/src/extend.o $(OBJDIR_DEBUG)/src/commons.o $(OBJDIR_DEBUG)/src/PartialDP_XDrop.o $(OBJDIR_DEBUG)/src/Node.o $(OBJDIR_DEBUG)/src/Indexer.o $(CFLAGS)

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/sequence_4bits.o $(OBJDIR_RELEASE)/src/parser.o $(OBJDIR_RELEASE)/src/misc_tools.o $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/src/listNodeUint16.o $(OBJDIR_RELEASE)/src/listNodeChar.o $(OBJDIR_RELEASE)/src/list.o $(OBJDIR_RELEASE)/src/Duo.o $(OBJDIR_RELEASE)/src/extendLevenshtein.o $(OBJDIR_RELEASE)/src/extend.o $(OBJDIR_RELEASE)/src/commons.o $(OBJDIR_RELEASE)/src/PartialDP_XDrop.o $(OBJDIR_RELEASE)/src/Node.o $(OBJDIR_RELEASE)/src/Indexer.o $(LDFLAGS)

all: judy libxml2 debug release

judy: 
	cd ./lib/judy-1.0.5; ./configure; make; make install

libxml2: 
	cd ./lib/libxml2-2.8.0; ./configure; make; make install

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LDFLAGS_DEBUG) $(LIBDIR_DEBUG) $(OBJ_DEBUG) -o $(OUT_DEBUG)

$(OBJDIR_DEBUG)/src/sequence_4bits.o: src/sequence_4bits.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/sequence_4bits.c -o $(OBJDIR_DEBUG)/src/sequence_4bits.o

$(OBJDIR_DEBUG)/src/parser.o: src/parser.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/parser.c -o $(OBJDIR_DEBUG)/src/parser.o

$(OBJDIR_DEBUG)/src/misc_tools.o: src/misc_tools.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/misc_tools.c -o $(OBJDIR_DEBUG)/src/misc_tools.o

$(OBJDIR_DEBUG)/src/main.o: src/main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.c -o $(OBJDIR_DEBUG)/src/main.o

$(OBJDIR_DEBUG)/src/listNodeUint16.o: src/listNodeUint16.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/listNodeUint16.c -o $(OBJDIR_DEBUG)/src/listNodeUint16.o

$(OBJDIR_DEBUG)/src/listNodeChar.o: src/listNodeChar.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/listNodeChar.c -o $(OBJDIR_DEBUG)/src/listNodeChar.o

$(OBJDIR_DEBUG)/src/list.o: src/list.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/list.c -o $(OBJDIR_DEBUG)/src/list.o

$(OBJDIR_DEBUG)/src/Duo.o: src/Duo.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Duo.c -o $(OBJDIR_DEBUG)/src/Duo.o

$(OBJDIR_DEBUG)/src/extendLevenshtein.o: src/extendLevenshtein.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/extendLevenshtein.c -o $(OBJDIR_DEBUG)/src/extendLevenshtein.o

$(OBJDIR_DEBUG)/src/extend.o: src/extend.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/extend.c -o $(OBJDIR_DEBUG)/src/extend.o

$(OBJDIR_DEBUG)/src/commons.o: src/commons.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/commons.c -o $(OBJDIR_DEBUG)/src/commons.o

$(OBJDIR_DEBUG)/src/PartialDP_XDrop.o: src/PartialDP_XDrop.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/PartialDP_XDrop.c -o $(OBJDIR_DEBUG)/src/PartialDP_XDrop.o

$(OBJDIR_DEBUG)/src/Node.o: src/Node.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Node.c -o $(OBJDIR_DEBUG)/src/Node.o

$(OBJDIR_DEBUG)/src/Indexer.o: src/Indexer.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Indexer.c -o $(OBJDIR_DEBUG)/src/Indexer.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LDFLAGS_RELEASE) $(LIBDIR_RELEASE) $(OBJ_RELEASE) $(INC_RELEASE) $(LIB_RELEASE) -o $(OUT_RELEASE)

$(OBJDIR_RELEASE)/src/sequence_4bits.o: src/sequence_4bits.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/sequence_4bits.c -o $(OBJDIR_RELEASE)/src/sequence_4bits.o

$(OBJDIR_RELEASE)/src/parser.o: src/parser.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/parser.c -o $(OBJDIR_RELEASE)/src/parser.o

$(OBJDIR_RELEASE)/src/misc_tools.o: src/misc_tools.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/misc_tools.c -o $(OBJDIR_RELEASE)/src/misc_tools.o

$(OBJDIR_RELEASE)/src/main.o: src/main.c
	$(CC) $(CFLAGS_RELEASE) $(LIB_RELEASE) $(INC_RELEASE) -c src/main.c -o $(OBJDIR_RELEASE)/src/main.o

$(OBJDIR_RELEASE)/src/listNodeUint16.o: src/listNodeUint16.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/listNodeUint16.c -o $(OBJDIR_RELEASE)/src/listNodeUint16.o

$(OBJDIR_RELEASE)/src/listNodeChar.o: src/listNodeChar.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/listNodeChar.c -o $(OBJDIR_RELEASE)/src/listNodeChar.o

$(OBJDIR_RELEASE)/src/list.o: src/list.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/list.c -o $(OBJDIR_RELEASE)/src/list.o

$(OBJDIR_RELEASE)/src/Duo.o: src/Duo.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Duo.c -o $(OBJDIR_RELEASE)/src/Duo.o

$(OBJDIR_RELEASE)/src/extendLevenshtein.o: src/extendLevenshtein.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/extendLevenshtein.c -o $(OBJDIR_RELEASE)/src/extendLevenshtein.o

$(OBJDIR_RELEASE)/src/extend.o: src/extend.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/extend.c -o $(OBJDIR_RELEASE)/src/extend.o

$(OBJDIR_RELEASE)/src/commons.o: src/commons.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/commons.c -o $(OBJDIR_RELEASE)/src/commons.o

$(OBJDIR_RELEASE)/src/PartialDP_XDrop.o: src/PartialDP_XDrop.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/PartialDP_XDrop.c -o $(OBJDIR_RELEASE)/src/PartialDP_XDrop.o

$(OBJDIR_RELEASE)/src/Node.o: src/Node.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Node.c -o $(OBJDIR_RELEASE)/src/Node.o

$(OBJDIR_RELEASE)/src/Indexer.o: src/Indexer.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Indexer.c -o $(OBJDIR_RELEASE)/src/Indexer.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

